version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ekonomvote_db_user
      POSTGRES_PASSWORD: ESZPgRBEPwwNDPAa0TgNkRqJYgk5aXP0KnTNt1PYjx
      POSTGRES_DB: ekonomvote_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ekonomvote_db_user -d ekonomvote_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge