# Generated by Django 5.1.6 on 2025-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samorzad', '0002_alter_candidate_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='winner',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
