# Generated by Django 4.2.1 on 2025-04-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samorzad', '0004_remove_candidate_info_electoralprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_vote_per_voting',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting',
        ),
        # Usunięto dodanie ograniczenia, które wywołuje błąd
        # migrations.AddConstraint(
        #     model_name='vote',
        #     constraint=models.UniqueConstraint(fields=('candidate_registration__voting', 'azure_user_id'), name='unique_user_vote_per_voting'),
        # ),
        migrations.AddField(
            model_name='candidateregistration',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='samorzad.candidate', null=True),
        ),
        migrations.AddField(
            model_name='candidateregistration',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_registrations', to='samorzad.voting', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='samorzad.candidateregistration', null=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='candidateregistration',
            constraint=models.UniqueConstraint(fields=('candidate', 'voting'), name='unique_candidate_per_voting'),
        ),
    ]