# Generated by Django 4.2.1 on 2025-04-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samorzad', '0006_alter_candidateregistration_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregistration',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='samorzad.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateregistration',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_registrations', to='samorzad.voting'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='samorzad.candidateregistration'),
        ),
    ]
