# Generated by Django 4.2.1 on 2025-04-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samorzad', '0007_alter_candidateregistration_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='school_class',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
