# Generated by Django 4.2.1 on 2025-04-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samorzad', '0008_candidate_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_eligible',
        ),
    ]
