from django.urls import path

from .views.panel import panel_login, panel_index, actions_list_main, partial_actions_list_table
from .views.samorzad import (
    add_empty_voting,
    samorzad_index,
    samorzad_add_candidate,
    samorzad_add_candidature,
    partial_candidates_search,
    list_candidates,
    list_candidatures,
    #read_voting,
    update_voting,
    update_candidate,
    update_candidature,
    delete_voting,
    delete_candidate,
    delete_candidature,
    redirect_to_candidature,
    partial_read_voting_list,
    partial_list_candidates,
    partial_list_candidatures
)
from .views.oscary import (
    create_voting_event,
    update_voting_event,
    delete_voting_event,
    list_voting_events,
    partial_list_voting_events,
    create_oscar,
    update_oscar,
    delete_oscar,
    list_oscars,
    partial_list_oscars,
    create_teacher,
    update_teacher,
    delete_teacher,
    list_teachers,
    partial_list_teachers,
    create_candidature,
    update_candidature,
    list_candidatures,
    partial_list_candidatures,
    delete_candidature
)


app_name = 'panel'

urlpatterns = [
    path('login/', panel_login, name='login'),
    path('index/', panel_index, name='index'),
    path('akcje/', actions_list_main, name="list_actions_main"),
    path('akcje-lista', partial_actions_list_table, name='list_actions_table'),
    #Samorząd
    path('samorzad/dodaj-glosowanie-puste', add_empty_voting, name='samorzad_add_empty_voting'),
    path('samorzad/dodaj-kandydata', samorzad_add_candidate, name="samorzad_add_candidate"),
    path('samorzad/dodaj-kandydature', samorzad_add_candidature, name='samorzad_add_candidature'),
    path('samorzad/', samorzad_index, name='samorzad_index'),
    path('samorzad/lista', partial_read_voting_list, name='partial_read_voting_list'),
    path('samorzad/lista-kandydatow', list_candidates, name='list_candidates'),
    path('samorzad/lista-kandydatow-search', partial_list_candidates, name='partial_list_candidates'),
    path('samorzad/lista-kandydatur', list_candidatures, name="list_candidatures"),
    path('samorzad/lista-kandydatur-search', partial_list_candidatures, name="partial_list_candidatures"),
    path('samorzad/glosowania/edytuj/<int:voting_id>', update_voting, name="update_voting"),
    path('samorzad/kandydaci/edytuj/<int:candidate_id>', update_candidate, name="update_candidate"),
    path('samorzad/kandydatury/edytuj/<int:candidature_id>', update_candidature, name="update_candidature"),
    path('samorzad/glosowania/usun', delete_voting, name="delete_voting"),
    path('samorzad/kandydaci/usun', delete_candidate, name="delete_candidate"),
    path('samorzad/kandydatury/usun', delete_candidature, name="delete_candidature"),
    path('samorzad/program-przekieruj/<int:electoral_program_id>', redirect_to_candidature, name="redirect_to_candidature"),
    # Partials
    path('samorzad/szukaj/kandydaci', partial_candidates_search, name='partial_candidates_search'),
    # Oscary
    path('oscary/dodaj/glosowanie', create_voting_event, name='create_voting_event'),
    path('oscary/edytuj/glosowanie/<int:voting_event_id>', update_voting_event, name='update_voting_event'),
    path('oscary/usun/glosowanie', delete_voting_event, name='delete_voting_event'),
    path('oscary/lista/glosowania', list_voting_events, name='list_voting_events'),
    path('oscary/partials/lista/glosowania', partial_list_voting_events, name='partial_list_voting_events'),
    path('oscary/dodaj/oscara', create_oscar, name="create_oscar"),
    path('oscary/edytuj/oscara/<int:oscar_id>', update_oscar, name="update_oscar"),
    path('oscary/usun/oscara', delete_oscar, name="delete_oscar"),
    path('oscary/lista/oscary', list_oscars, name="list_oscars"),
    path('oscary/partials/lista/oscary', partial_list_oscars, name="partial_list_oscars"),
    path('oscary/dodaj/nauczyciela', create_teacher, name="create_teacher"),
    path('oscary/edytuj/nauczyciela/<int:teacher_id>', update_teacher, name="update_teacher"),
    path('oscary/usun/nauczyciela', delete_teacher, name="delete_teacher"),
    path('oscary/lista/nauczyciele', list_teachers, name="list_teachers"),
    path('oscary/partials/lista/nauczyciele', partial_list_teachers, name="partial_list_teachers"),
    path('oscary/dodaj/kandydature', create_candidature, name="create_candidature"),
    path('oscary/edytuj/kandydature/<int:candidature_id>', update_candidature, name="update_candidature"),
    path('oscary/lista/kandydatury', list_candidatures, name="list_candidatures"),
    path('oscary/partials/lista/kandydatury', partial_list_candidatures, name="partial_list_candidatures"),
    path('oscary/usun/kandydatura', delete_candidature, name="delete_candidature"),
    # path('oscary/dodaj-nauczyciela', create_teacher, name="create_teacher"),
    # path('oscary/dodaj-kandydature', create_candidature, name='create_candidature'),
    # path('oscary/', read_voting_event_list, name='read_voting_event_list'),
    # path('oscary/p', partial_read_voting_list_event, name='partial_read_voting_list'),
    # path('oscary/lista-nauczycieli', partial_list_teachers, name='partial_list_teachers'),
    # path('samorzad/lista-nauczycieli-p', partial_list_candidates, name='partial_list_candidates'),
    # path('samorzad/lista-kandydatur', list_candidatures, name="list_candidatures"),
    # path('samorzad/lista-kandydatur-search', partial_list_candidatures, name="partial_list_candidatures"),
    # path('samorzad/glosowania/edytuj/<int:voting_id>', update_voting, name="update_voting"),
    # path('samorzad/kandydaci/edytuj/<int:candidate_id>', update_candidate, name="update_candidate"),
    # path('samorzad/kandydatury/edytuj/<int:candidature_id>', update_candidature, name="update_candidature"),
    # path('samorzad/glosowania/usun', delete_voting, name="delete_voting"),
    # path('samorzad/kandydaci/usun', delete_candidate, name="delete_candidate"),
    # path('samorzad/kandydatury/usun', delete_candidature, name="delete_candidature"),
    # path('samorzad/program-przekieruj/<int:electoral_program_id>', redirect_to_candidature,
    #      name="redirect_to_candidature"),
    # # Partials
    # path('samorzad/szukaj/kandydaci', partial_candidates_search, name='partial_candidates_search')
]